server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        worksChannel:
          binder: rabbit
          destination: work.exchange
          contentType: application/json
          group: testgroup